#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ENV_DIR=${DIR}/../.env

VAULT_CONFIG_FILE=${ENV_DIR}/config/vault.env

# Create config file
mkdir -p ${ENV_DIR}/config
echo "# This file was autogenerated! Don't edit it!" > ${VAULT_CONFIG_FILE}
echo "VAULT_ADDR='${VAULT_ADDR}'" >> ${VAULT_CONFIG_FILE}
echo "VAULT_TOKEN='${VAULT_TOKEN}'" >> ${VAULT_CONFIG_FILE}
